# Generated by Django 5.1.15 on 2026-04-29 04:16

import apps.briefing.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('methodology', '0004_frasedevolutiva_pergunta_arquetipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BriefingSessao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador único')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído (soft)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('token', models.CharField(default=apps.briefing.models._gerar_token, help_text='URL-safe. Não exibe PK interno.', max_length=64, unique=True, verbose_name='Token público')),
                ('nome_empresa', models.CharField(blank=True, help_text='Captura quando informado durante o briefing.', max_length=200, verbose_name='Nome da empresa')),
                ('nome_respondente', models.CharField(blank=True, max_length=160, verbose_name='Nome do respondente')),
                ('email_respondente', models.EmailField(blank=True, help_text='Usado para link mágico de retorno e devolutiva.', max_length=254, verbose_name='E-mail do respondente')),
                ('status', models.CharField(choices=[('iniciada', 'Iniciada'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('abandonada', 'Abandonada')], db_index=True, default='iniciada', max_length=16, verbose_name='Status')),
                ('perfil_calculado', models.CharField(blank=True, choices=[('light', 'Light'), ('standard', 'Standard'), ('deep', 'Deep'), ('enterprise', 'Enterprise')], help_text='Resultado do Score Composto de Aprofundamento.', max_length=16, verbose_name='Perfil calculado (SCA)')),
                ('ato_atual', models.CharField(blank=True, max_length=32, verbose_name='Slug do ato atual')),
                ('iniciada_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Iniciada em')),
                ('concluida_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('ultima_atividade_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última atividade em')),
                ('devolutiva_json', models.JSONField(blank=True, help_text='Saída da engine de síntese. Preenchido ao concluir.', null=True, verbose_name='Devolutiva (JSON)')),
                ('origem', models.CharField(blank=True, help_text='UTM/canal de origem (campanha, link direto, indicação, etc.).', max_length=80, verbose_name='Origem')),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('pergunta_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='methodology.pergunta', verbose_name='Pergunta atual')),
                ('roteiro_versao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='methodology.roteiroversao', verbose_name='Versão do roteiro (pinada)')),
            ],
            options={
                'verbose_name': 'Sessão de briefing',
                'verbose_name_plural': 'Sessões de briefing',
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.CreateModel(
            name='EventoBriefing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador único')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído (soft)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('tipo', models.CharField(choices=[('sessao_iniciada', 'Sessão iniciada'), ('perfil_calculado', 'Perfil calculado'), ('pergunta_respondida', 'Pergunta respondida'), ('pergunta_pulada', 'Pergunta pulada'), ('ato_concluido', 'Ato concluído'), ('insight_disparado', 'Insight disparado'), ('sintese_gerada', 'Síntese gerada'), ('sessao_concluida', 'Sessão concluída'), ('sessao_retomada', 'Sessão retomada')], max_length=32, verbose_name='Tipo')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Detalhes do evento.', verbose_name='Payload')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='briefing.briefingsessao', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Evento de briefing',
                'verbose_name_plural': 'Eventos de briefing',
                'ordering': ['sessao', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RespostaPergunta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador único')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído (soft)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('pergunta_codigo', models.CharField(max_length=16, verbose_name='Código (snapshot)')),
                ('pergunta_texto', models.TextField(verbose_name='Texto público (snapshot)')),
                ('pergunta_tipo', models.CharField(max_length=32, verbose_name='Tipo (snapshot)')),
                ('valor', models.JSONField(help_text="Formato depende do tipo: escolha_unica → 'codigo_opcao'; escolha_multipla → ['codigo_opcao_1', ...]; texto → 'texto livre'; escala → int.", verbose_name='Valor da resposta')),
                ('pulada', models.BooleanField(default=False, help_text='True se cliente optou por pular pergunta opcional.', verbose_name='Pulada')),
                ('versao', models.PositiveSmallIntegerField(default=1, help_text='Cliente pode revisar e re-responder. Maior versão = mais recente.', verbose_name='Versão')),
                ('tempo_ate_responder_ms', models.PositiveIntegerField(blank=True, help_text='Telemetria: tempo desde apresentação até envio.', null=True, verbose_name='Tempo até responder (ms)')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='methodology.pergunta', verbose_name='Pergunta')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='briefing.briefingsessao', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Resposta de pergunta',
                'verbose_name_plural': 'Respostas de pergunta',
                'ordering': ['sessao', 'pergunta', '-versao'],
            },
        ),
        migrations.CreateModel(
            name='SinalCapturado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador único')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído (soft)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('valor', models.JSONField(verbose_name='Valor capturado')),
                ('peso', models.FloatField(default=1.0, help_text='Cópia do peso do mapeamento, para auditoria.', verbose_name='Peso aplicado')),
                ('origem_resposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinais_gerados', to='briefing.respostapergunta', verbose_name='Resposta de origem')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinais', to='briefing.briefingsessao', verbose_name='Sessão')),
                ('sinal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capturas', to='methodology.catalogosinal', verbose_name='Sinal (catálogo)')),
            ],
            options={
                'verbose_name': 'Sinal capturado',
                'verbose_name_plural': 'Sinais capturados',
                'ordering': ['sessao', 'sinal'],
            },
        ),
        migrations.AddIndex(
            model_name='briefingsessao',
            index=models.Index(fields=['token'], name='briefing_br_token_aa71f8_idx'),
        ),
        migrations.AddIndex(
            model_name='briefingsessao',
            index=models.Index(fields=['status', '-iniciada_em'], name='briefing_br_status_91e802_idx'),
        ),
        migrations.AddIndex(
            model_name='briefingsessao',
            index=models.Index(fields=['roteiro_versao', 'status'], name='briefing_br_roteiro_f55fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='briefingsessao',
            index=models.Index(fields=['email_respondente'], name='briefing_br_email_r_71d6e9_idx'),
        ),
        migrations.AddIndex(
            model_name='eventobriefing',
            index=models.Index(fields=['sessao', 'created_at'], name='briefing_ev_sessao__0503a5_idx'),
        ),
        migrations.AddIndex(
            model_name='eventobriefing',
            index=models.Index(fields=['tipo'], name='briefing_ev_tipo_48b631_idx'),
        ),
        migrations.AddIndex(
            model_name='respostapergunta',
            index=models.Index(fields=['sessao', 'pergunta'], name='briefing_re_sessao__ef5a87_idx'),
        ),
        migrations.AddIndex(
            model_name='respostapergunta',
            index=models.Index(fields=['pergunta_codigo'], name='briefing_re_pergunt_340a76_idx'),
        ),
        migrations.AddConstraint(
            model_name='respostapergunta',
            constraint=models.UniqueConstraint(fields=('sessao', 'pergunta', 'versao'), name='uniq_resposta_sessao_pergunta_versao'),
        ),
        migrations.AddIndex(
            model_name='sinalcapturado',
            index=models.Index(fields=['sessao', 'sinal'], name='briefing_si_sessao__bdbdb2_idx'),
        ),
        migrations.AddIndex(
            model_name='sinalcapturado',
            index=models.Index(fields=['sinal'], name='briefing_si_sinal_i_a4681e_idx'),
        ),
    ]
