# Generated by Django 5.1.15 on 2026-04-28 07:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoteiroIdentidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador único')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído (soft)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('nome', models.CharField(help_text="Nome humano (ex: 'Roteiro Universal Ferzion').", max_length=120, verbose_name='Nome do roteiro')),
                ('slug', models.SlugField(help_text='Identificador URL-friendly. Gerado automaticamente se vazio.', max_length=140, unique=True, verbose_name='Slug')),
                ('tipo', models.CharField(choices=[('universal', 'Universal'), ('logistica', 'Logística'), ('saude', 'Saúde'), ('agro', 'Agronegócio'), ('juridico', 'Jurídico'), ('industria', 'Indústria'), ('rh', 'Recursos Humanos'), ('varejo', 'Varejo'), ('saas', 'SaaS')], default='universal', max_length=32, verbose_name='Tipo')),
                ('descricao_interna', models.TextField(blank=True, help_text='Notas internas da Ferzion (não aparecem para o cliente).', verbose_name='Descrição interna')),
                ('is_active', models.BooleanField(default=True, help_text='Identidade inativa não aparece para novos briefings.', verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Roteiro (identidade)',
                'verbose_name_plural': 'Roteiros (identidades)',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['slug'], name='methodology_slug_c8cf4d_idx'), models.Index(fields=['tipo', 'is_active'], name='methodology_tipo_22d46e_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoteiroVersao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador único')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído (soft)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('version', models.PositiveIntegerField(help_text='Sequencial dentro da identidade. Gerado automaticamente.', verbose_name='Número da versão')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicada'), ('archived', 'Arquivada')], db_index=True, default='draft', max_length=16, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicada em')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Arquivada em')),
                ('snapshot_json', models.JSONField(blank=True, help_text='Estrutura completa congelada. Preenchido na publicação.', null=True, verbose_name='Snapshot')),
                ('notas_da_versao', models.TextField(blank=True, help_text="Changelog / notas internas (ex: 'Refinada pergunta 3.6').", verbose_name='Notas desta versão')),
                ('identidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versoes', to='methodology.roteiroidentidade', verbose_name='Identidade')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roteiros_publicados', to=settings.AUTH_USER_MODEL, verbose_name='Publicada por')),
            ],
            options={
                'verbose_name': 'Versão de roteiro',
                'verbose_name_plural': 'Versões de roteiro',
                'ordering': ['-identidade', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Ato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador único')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído (soft)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('slug', models.CharField(choices=[('acolhimento', 'Acolhimento'), ('calibracao', 'Calibração'), ('compreensao', 'Compreensão do Negócio'), ('diagnostico', 'Diagnóstico Operacional'), ('aspiracoes', 'Aspirações e Visão'), ('restricoes', 'Restrições e Realidade'), ('sintese', 'Síntese e Devolutiva'), ('ponte', 'Ponte para o Painel')], help_text='Identificador canônico do ato (contrato com frontend).', max_length=32, verbose_name='Slug do ato')),
                ('ordem', models.PositiveSmallIntegerField(help_text='Posição na sequência narrativa (0, 1, 2, ...).', verbose_name='Ordem')),
                ('titulo_publico', models.CharField(help_text='Aparece para o cliente. Tom Ferzion: humano, claro.', max_length=200, verbose_name='Título público')),
                ('subtitulo_publico', models.CharField(blank=True, help_text='Frase de apoio que aparece abaixo do título.', max_length=400, verbose_name='Subtítulo público')),
                ('introducao_publica', models.TextField(blank=True, help_text='Texto introdutório longo (opcional). Markdown aceito.', verbose_name='Introdução pública')),
                ('descricao_interna', models.TextField(blank=True, help_text='Notas/objetivos internos do ato. Não aparece para o cliente.', verbose_name='Descrição interna')),
                ('obrigatorio', models.BooleanField(default=True, help_text='Se desmarcado, este ato pode ser pulado por certos perfis.', verbose_name='Obrigatório')),
                ('configuracao', models.JSONField(blank=True, default=dict, help_text='Configurações comportamentais específicas (JSON).', verbose_name='Configuração')),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atos', to='methodology.roteiroversao', verbose_name='Versão')),
            ],
            options={
                'verbose_name': 'Ato',
                'verbose_name_plural': 'Atos',
                'ordering': ['versao', 'ordem'],
            },
        ),
        migrations.AddIndex(
            model_name='roteiroversao',
            index=models.Index(fields=['identidade', 'status'], name='methodology_identid_bc9d1f_idx'),
        ),
        migrations.AddIndex(
            model_name='roteiroversao',
            index=models.Index(fields=['status'], name='methodology_status_c1002c_idx'),
        ),
        migrations.AddConstraint(
            model_name='roteiroversao',
            constraint=models.UniqueConstraint(fields=('identidade', 'version'), name='uniq_identidade_versao'),
        ),
        migrations.AddConstraint(
            model_name='roteiroversao',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('identidade',), name='uniq_draft_por_identidade'),
        ),
        migrations.AddConstraint(
            model_name='roteiroversao',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('identidade',), name='uniq_published_por_identidade'),
        ),
        migrations.AddIndex(
            model_name='ato',
            index=models.Index(fields=['versao', 'ordem'], name='methodology_versao__838e2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='ato',
            constraint=models.UniqueConstraint(fields=('versao', 'slug'), name='uniq_ato_slug_por_versao'),
        ),
        migrations.AddConstraint(
            model_name='ato',
            constraint=models.UniqueConstraint(fields=('versao', 'ordem'), name='uniq_ato_ordem_por_versao'),
        ),
    ]
