# Generated by Django 5.1.15 on 2026-04-28 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ato',
            name='ordem',
            field=models.PositiveSmallIntegerField(verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='ato',
            name='subtitulo_publico',
            field=models.CharField(blank=True, max_length=400, verbose_name='Subtítulo público'),
        ),
        migrations.CreateModel(
            name='CatalogoSinal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador único')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído (soft)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('chave', models.SlugField(help_text="Identificador snake_case do sinal (ex: 'porte_operacional').", max_length=80, unique=True, verbose_name='Chave')),
                ('nome', models.CharField(help_text='Nome legível (aparece no admin e em relatórios técnicos).', max_length=160, verbose_name='Nome')),
                ('descricao', models.TextField(help_text='O que este sinal representa? Quando é capturado?', verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('perfil', 'Perfil do cliente'), ('negocio', 'Modelo de negócio'), ('operacao', 'Operação'), ('dor', 'Dor / risco'), ('aspiracao', 'Aspiração / visão'), ('restricao', 'Restrição'), ('meta', 'Meta-sinal (calibração interna)')], default='operacao', max_length=32, verbose_name='Categoria')),
                ('tipo_valor', models.CharField(choices=[('categorico', "Categórico (ex: 'alto', 'médio', 'baixo')"), ('escala', 'Escala numérica (ex: 1-5)'), ('booleano', 'Booleano (verdadeiro/falso)'), ('numerico', 'Numérico livre'), ('texto', 'Texto preservado')], max_length=16, verbose_name='Tipo do valor')),
                ('valores_validos', models.JSONField(blank=True, default=list, help_text='Domínio do sinal. Para CATEGORICO: lista de strings. Para ESCALA: [min, max]. Para BOOLEANO: ignora. Para TEXTO/NUMERICO: ignora (validação livre).', verbose_name='Valores válidos')),
                ('notas_internas', models.TextField(blank=True, help_text='Histórico de mudanças, justificativas, contexto da definição. Editar com cuidado — afeta interpretação histórica.', verbose_name='Notas internas')),
            ],
            options={
                'verbose_name': 'Sinal (catálogo)',
                'verbose_name_plural': 'Sinais (catálogo)',
                'ordering': ['categoria', 'chave'],
                'indexes': [models.Index(fields=['categoria'], name='methodology_categor_ac3712_idx')],
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador único')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído (soft)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('codigo', models.CharField(help_text="Identificador legível (ex: '1.7', '3.2', '2A.1').", max_length=16, verbose_name='Código')),
                ('ordem', models.PositiveSmallIntegerField(help_text='Posição da pergunta dentro do ato.', verbose_name='Ordem')),
                ('tipo', models.CharField(choices=[('texto_curto', 'Texto curto (1 linha)'), ('texto_longo', 'Texto longo (várias linhas)'), ('escolha_unica', 'Escolha única (radio)'), ('escolha_multipla', 'Escolha múltipla (checkboxes)'), ('escala', 'Escala (1-N)'), ('escolha_unica_com_outro', "Escolha única + 'Outro'"), ('upload', 'Upload de arquivo (futuro)'), ('ranking', 'Ranking / ordenação (futuro)'), ('matriz', 'Matriz visual (futuro)'), ('condicional', 'Condicional avançada (futuro)'), ('conversacional', 'Bloco conversacional (futuro)'), ('audio', 'Áudio / voz (futuro)')], max_length=32, verbose_name='Tipo de pergunta')),
                ('texto_publico', models.TextField(help_text='O enunciado que o cliente lê.', verbose_name='Texto público')),
                ('placeholder', models.CharField(blank=True, help_text='Texto-guia dentro do campo (apenas tipos texto_*).', max_length=300, verbose_name='Placeholder')),
                ('helper_text', models.CharField(blank=True, help_text='Microcopy abaixo do campo. Tom Ferzion.', max_length=300, verbose_name='Texto de ajuda')),
                ('objetivo_interno', models.TextField(blank=True, help_text='O que esta pergunta busca descobrir? (não aparece para o cliente)', verbose_name='Objetivo interno')),
                ('obrigatoria', models.BooleanField(default=True, help_text='Se desmarcada, o cliente pode pular.', verbose_name='Obrigatória')),
                ('perfis_minimos', models.JSONField(blank=True, default=list, help_text="Lista de perfis nos quais a pergunta aparece. Ex: ['standard', 'deep', 'enterprise']. Vazio = aparece em todos os perfis.", verbose_name='Perfis mínimos')),
                ('precondicoes', models.JSONField(blank=True, default=dict, help_text='Condições para a pergunta aparecer (baseadas em sinais já capturados). JSON estruturado — ver docs.', verbose_name='Pré-condições')),
                ('tipo_config', models.JSONField(blank=True, default=dict, help_text="JSON com schema dependente do tipo. Exemplos: texto_curto → {'max_chars': 200}; escala → {'min': 1, 'max': 5, 'rotulos': {'1': 'Discordo'}}; escolha_unica_com_outro → {'rotulo_outro': 'Outro: descreva'}.", verbose_name='Configuração do tipo')),
                ('ato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='methodology.ato', verbose_name='Ato')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ['ato', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='OpcaoDePergunta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador único')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído (soft)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('codigo_interno', models.CharField(help_text="Identificador estável da opção (ex: 'porte_micro', 'modelo_recorrente'). Usado em mapeamentos de sinal.", max_length=64, verbose_name='Código interno')),
                ('ordem', models.PositiveSmallIntegerField(verbose_name='Ordem')),
                ('texto_publico', models.CharField(help_text='O que o cliente lê.', max_length=300, verbose_name='Texto público')),
                ('descricao_publica', models.CharField(blank=True, help_text='Descrição secundária opcional (aparece menor).', max_length=400, verbose_name='Descrição pública')),
                ('icone', models.CharField(blank=True, help_text="Nome do ícone (ex: 'building', 'user'). Opcional.", max_length=64, verbose_name='Ícone')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='methodology.pergunta', verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Opção de pergunta',
                'verbose_name_plural': 'Opções de pergunta',
                'ordering': ['pergunta', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='MapeamentoDeSinal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador único')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído (soft)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('condicao', models.JSONField(help_text='JSON da condição. Ex: {"operador": "in", "valores": ["uuid_opt_a"]}. Operadores: in, equals, contains, always.', verbose_name='Condição')),
                ('valor_extraido', models.JSONField(help_text='Valor a atribuir ao sinal quando a condição é satisfeita. Deve ser válido para o tipo do sinal.', verbose_name='Valor extraído')),
                ('peso', models.FloatField(default=1.0, help_text='Peso desta extração quando o sinal é agregado. 1.0 = peso normal. Use < 1.0 para regras secundárias.', verbose_name='Peso')),
                ('notas', models.TextField(blank=True, help_text='Justificativa da regra. Útil para revisão futura.', verbose_name='Notas')),
                ('sinal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapeamentos', to='methodology.catalogosinal', verbose_name='Sinal')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeamentos', to='methodology.pergunta', verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Mapeamento de sinal',
                'verbose_name_plural': 'Mapeamentos de sinal',
                'ordering': ['pergunta', 'sinal'],
            },
        ),
        migrations.AddIndex(
            model_name='pergunta',
            index=models.Index(fields=['ato', 'ordem'], name='methodology_ato_id_b9fca7_idx'),
        ),
        migrations.AddIndex(
            model_name='pergunta',
            index=models.Index(fields=['tipo'], name='methodology_tipo_ae5819_idx'),
        ),
        migrations.AddConstraint(
            model_name='pergunta',
            constraint=models.UniqueConstraint(fields=('ato', 'codigo'), name='uniq_pergunta_codigo_por_ato'),
        ),
        migrations.AddConstraint(
            model_name='pergunta',
            constraint=models.UniqueConstraint(fields=('ato', 'ordem'), name='uniq_pergunta_ordem_por_ato'),
        ),
        migrations.AddIndex(
            model_name='opcaodepergunta',
            index=models.Index(fields=['pergunta', 'ordem'], name='methodology_pergunt_0cc120_idx'),
        ),
        migrations.AddConstraint(
            model_name='opcaodepergunta',
            constraint=models.UniqueConstraint(fields=('pergunta', 'codigo_interno'), name='uniq_opcao_codigo_por_pergunta'),
        ),
        migrations.AddConstraint(
            model_name='opcaodepergunta',
            constraint=models.UniqueConstraint(fields=('pergunta', 'ordem'), name='uniq_opcao_ordem_por_pergunta'),
        ),
        migrations.AddIndex(
            model_name='mapeamentodesinal',
            index=models.Index(fields=['pergunta'], name='methodology_pergunt_bfc53d_idx'),
        ),
        migrations.AddIndex(
            model_name='mapeamentodesinal',
            index=models.Index(fields=['sinal'], name='methodology_sinal_i_7e416c_idx'),
        ),
    ]
