# Generated by Django 5.1.15 on 2026-04-28 10:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodology', '0002_alter_ato_ordem_alter_ato_subtitulo_publico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ato',
            name='configuracao',
            field=models.JSONField(blank=True, default=dict, verbose_name='Configuração'),
        ),
        migrations.AlterField(
            model_name='ato',
            name='descricao_interna',
            field=models.TextField(blank=True, verbose_name='Descrição interna'),
        ),
        migrations.AlterField(
            model_name='ato',
            name='introducao_publica',
            field=models.TextField(blank=True, verbose_name='Introdução pública'),
        ),
        migrations.AlterField(
            model_name='ato',
            name='obrigatorio',
            field=models.BooleanField(default=True, verbose_name='Obrigatório'),
        ),
        migrations.AlterField(
            model_name='ato',
            name='slug',
            field=models.CharField(choices=[('acolhimento', 'Acolhimento'), ('calibracao', 'Calibração'), ('compreensao', 'Compreensão do Negócio'), ('diagnostico', 'Diagnóstico Operacional'), ('aspiracoes', 'Aspirações e Visão'), ('restricoes', 'Restrições e Realidade'), ('sintese', 'Síntese e Devolutiva'), ('ponte', 'Ponte para o Painel')], max_length=32, verbose_name='Slug do ato'),
        ),
        migrations.AlterField(
            model_name='ato',
            name='titulo_publico',
            field=models.CharField(max_length=200, verbose_name='Título público'),
        ),
        migrations.AlterField(
            model_name='catalogosinal',
            name='chave',
            field=models.SlugField(help_text='Identificador snake_case do sinal.', max_length=80, unique=True, verbose_name='Chave'),
        ),
        migrations.AlterField(
            model_name='catalogosinal',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='catalogosinal',
            name='nome',
            field=models.CharField(max_length=160, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='catalogosinal',
            name='notas_internas',
            field=models.TextField(blank=True, verbose_name='Notas internas'),
        ),
        migrations.AlterField(
            model_name='catalogosinal',
            name='tipo_valor',
            field=models.CharField(choices=[('categorico', 'Categórico'), ('escala', 'Escala numérica'), ('booleano', 'Booleano'), ('numerico', 'Numérico livre'), ('texto', 'Texto preservado')], max_length=16, verbose_name='Tipo do valor'),
        ),
        migrations.AlterField(
            model_name='catalogosinal',
            name='valores_validos',
            field=models.JSONField(blank=True, default=list, verbose_name='Valores válidos'),
        ),
        migrations.AlterField(
            model_name='mapeamentodesinal',
            name='condicao',
            field=models.JSONField(verbose_name='Condição'),
        ),
        migrations.AlterField(
            model_name='mapeamentodesinal',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='mapeamentodesinal',
            name='peso',
            field=models.FloatField(default=1.0, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='mapeamentodesinal',
            name='valor_extraido',
            field=models.JSONField(verbose_name='Valor extraído'),
        ),
        migrations.AlterField(
            model_name='opcaodepergunta',
            name='codigo_interno',
            field=models.CharField(help_text="Identificador estável da opção (ex: 'porte_micro').", max_length=64, verbose_name='Código interno'),
        ),
        migrations.AlterField(
            model_name='opcaodepergunta',
            name='descricao_publica',
            field=models.CharField(blank=True, max_length=400, verbose_name='Descrição pública'),
        ),
        migrations.AlterField(
            model_name='opcaodepergunta',
            name='icone',
            field=models.CharField(blank=True, max_length=64, verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='opcaodepergunta',
            name='texto_publico',
            field=models.CharField(max_length=300, verbose_name='Texto público'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='codigo',
            field=models.CharField(max_length=16, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='helper_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Texto de ajuda'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='objetivo_interno',
            field=models.TextField(blank=True, verbose_name='Objetivo interno'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='obrigatoria',
            field=models.BooleanField(default=True, verbose_name='Obrigatória'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='ordem',
            field=models.PositiveSmallIntegerField(verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='perfis_minimos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de perfis nos quais a pergunta aparece. Vazio = todos.', verbose_name='Perfis mínimos'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='placeholder',
            field=models.CharField(blank=True, max_length=300, verbose_name='Placeholder'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='precondicoes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Pré-condições'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='texto_publico',
            field=models.TextField(verbose_name='Texto público'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='tipo_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Configuração do tipo'),
        ),
        migrations.AlterField(
            model_name='roteiroidentidade',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='roteiroversao',
            name='notas_da_versao',
            field=models.TextField(blank=True, help_text='Changelog / notas internas.', verbose_name='Notas desta versão'),
        ),
        migrations.AlterField(
            model_name='roteiroversao',
            name='version',
            field=models.PositiveIntegerField(verbose_name='Número da versão'),
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador único')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído (soft)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('codigo', models.SlugField(help_text='Identificador snake_case dentro da versão.', max_length=80, verbose_name='Código')),
                ('titulo_publico', models.CharField(help_text='Título curto que aparece no card de insight.', max_length=200, verbose_name='Título público')),
                ('texto_publico', models.TextField(help_text='Mensagem do insight. Tom Ferzion. Pode usar {nome_empresa} ou {valor_sinal:porte_operacional}.', verbose_name='Texto público')),
                ('severidade', models.CharField(choices=[('info', 'Informativo'), ('atencao', 'Atenção'), ('critico', 'Crítico'), ('positivo', 'Positivo')], default='info', max_length=16, verbose_name='Severidade')),
                ('categoria', models.CharField(choices=[('governanca', 'Governança'), ('operacional', 'Operacional'), ('comercial', 'Comercial'), ('financeiro', 'Financeiro'), ('tecnologico', 'Tecnológico'), ('humano', 'Pessoas / RH'), ('estrategico', 'Estratégico')], default='operacional', max_length=24, verbose_name='Categoria')),
                ('momento_disparo', models.CharField(choices=[('durante_ato', 'Durante um ato (ao vivo)'), ('sintese_final', 'Apenas no Ato 6'), ('ambos', 'Durante ato e na síntese')], default='ambos', max_length=16, verbose_name='Momento de disparo')),
                ('condicoes', models.JSONField(default=dict, help_text='Ex: {"operador": "and", "clausulas": [...]}.', verbose_name='Condições de disparo')),
                ('prioridade', models.PositiveSmallIntegerField(default=50, help_text='0-100. Maior = aparece primeiro quando vários disparam.', verbose_name='Prioridade')),
                ('limite_simultaneos', models.PositiveSmallIntegerField(default=0, help_text='0 = sem limite.', verbose_name='Limite simultâneo')),
                ('objetivo_interno', models.TextField(blank=True, verbose_name='Objetivo interno')),
                ('ato_de_disparo', models.ForeignKey(blank=True, help_text='Se o momento permite ao vivo, em qual ato disparar?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights_ao_vivo', to='methodology.ato', verbose_name='Ato (para disparo ao vivo)')),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='methodology.roteiroversao', verbose_name='Versão do roteiro')),
            ],
            options={
                'verbose_name': 'Insight',
                'verbose_name_plural': 'Insights',
                'ordering': ['versao', 'categoria', '-prioridade'],
                'indexes': [models.Index(fields=['versao', 'categoria'], name='methodology_versao__346be9_idx'), models.Index(fields=['versao', 'momento_disparo'], name='methodology_versao__0cd3bb_idx'), models.Index(fields=['severidade'], name='methodology_severid_69a671_idx')],
                'constraints': [models.UniqueConstraint(fields=('versao', 'codigo'), name='uniq_insight_codigo_por_versao')],
            },
        ),
        migrations.CreateModel(
            name='RegraDeSintese',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador único')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído (soft)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('codigo', models.SlugField(max_length=80, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('frase_sintese', 'Frase-síntese principal'), ('score_maturidade', 'Score de maturidade digital'), ('oportunidade', 'Oportunidade identificada'), ('proximo_passo', 'Próximo passo recomendado'), ('modulo_sugerido', 'Módulo de sistema sugerido'), ('risco_operacional', 'Risco operacional')], max_length=24, verbose_name='Tipo')),
                ('titulo_interno', models.CharField(help_text='Como aparece no admin.', max_length=160, verbose_name='Título interno')),
                ('template', models.TextField(help_text='Texto renderizado quando a regra é aplicada. Aceita variáveis no formato {variavel}.', verbose_name='Template')),
                ('condicoes', models.JSONField(default=dict, verbose_name='Condições de aplicação')),
                ('prioridade', models.PositiveSmallIntegerField(default=50, verbose_name='Prioridade')),
                ('perfis_aplicaveis', models.JSONField(blank=True, default=list, help_text='Vazio = todos os perfis.', verbose_name='Perfis aplicáveis')),
                ('impacto_estimado', models.CharField(blank=True, help_text="Para regras de oportunidade. Ex: 'alto', 'medio', 'baixo'.", max_length=32, verbose_name='Impacto estimado')),
                ('modulo_sugerido_codigo', models.SlugField(blank=True, help_text="Para regras de oportunidade ou módulo. Ex: 'crm_basico'.", max_length=80, verbose_name='Código de módulo sugerido')),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_de_sintese', to='methodology.roteiroversao', verbose_name='Versão do roteiro')),
            ],
            options={
                'verbose_name': 'Regra de síntese',
                'verbose_name_plural': 'Regras de síntese',
                'ordering': ['versao', 'tipo', '-prioridade'],
                'indexes': [models.Index(fields=['versao', 'tipo'], name='methodology_versao__80a3fb_idx')],
                'constraints': [models.UniqueConstraint(fields=('versao', 'codigo'), name='uniq_regra_codigo_por_versao')],
            },
        ),
    ]
