# Generated by Django 5.1.15 on 2026-04-28 22:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodology', '0003_alter_ato_configuracao_alter_ato_descricao_interna_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraseDevolutiva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador único')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído (soft)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('faixa', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], max_length=8, verbose_name='Faixa')),
                ('texto', models.TextField(help_text='Frase exibida na devolutiva quando o sinal cair nesta faixa.', verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Frase de devolutiva',
                'verbose_name_plural': 'Frases de devolutiva',
                'ordering': ['pergunta', 'faixa'],
            },
        ),
        migrations.AddField(
            model_name='pergunta',
            name='arquetipo',
            field=models.CharField(choices=[('calibradora', 'Calibradora'), ('reveladora', 'Reveladora'), ('mapeadora', 'Mapeadora'), ('confrontadora', 'Confrontadora')], default='calibradora', help_text='Função metodológica: Calibradora (classifica), Reveladora (texto livre), Mapeadora (múltiplas marcações), Confrontadora (gera consciência).', max_length=24, verbose_name='Arquétipo'),
        ),
        migrations.AddIndex(
            model_name='pergunta',
            index=models.Index(fields=['arquetipo'], name='methodology_arqueti_b635a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='mapeamentodesinal',
            constraint=models.UniqueConstraint(fields=('pergunta', 'sinal', 'valor_extraido'), name='uniq_mapeamento_pergunta_sinal_valor'),
        ),
        migrations.AddField(
            model_name='frasedevolutiva',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frases_devolutiva', to='methodology.pergunta', verbose_name='Pergunta'),
        ),
        migrations.AddConstraint(
            model_name='frasedevolutiva',
            constraint=models.UniqueConstraint(fields=('pergunta', 'faixa'), name='uniq_frase_faixa_por_pergunta'),
        ),
    ]
